# -*- coding: utf-8 -*-
"""Krishna_S405010_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LjsVR0Kr74m-im7IFzr0UQQ_Mttzorm1
"""

# =====================================================================
# OBJECTIVE 1 — ANALYTIC TASK: Assists by Player Position
# Comparing average assists between Forwards and Midfielders
# FIFA World Cup 2026 — HIT140 Foundations of Data Science
# =====================================================================
#
# Research question:
# Did forwards and midfielders differ significantly in their average
# number of assists among players who recorded at least one goal or
# assist at the 2026 FIFA World Cup?
#
# H0: mean assists (Forward) = mean assists (Midfielder)
# H1: mean assists (Forward) != mean assists (Midfielder)
# alpha = 0.05, two-tailed, Welch's independent two-sample t-test


# ---------------------------------------------------------------------

# 1. DATA LOADING
# ---------------------------------------------------------------------
import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt

url = "https://raw.githubusercontent.com/Bustami/efi-fifa-data-wc-2026/refs/heads/master/data/wc2026_efi.csv"
player_match_df = pd.read_csv(url)

print("Dataset loaded. Shape:", player_match_df.shape)
display(player_match_df.head())


# ---------------------------------------------------------------------

# 2. DATA INSPECTION
# ---------------------------------------------------------------------
print("Unique players:", player_match_df["player_id"].nunique())
print("Unique matches:", player_match_df["match_id"].nunique())
print("Rows (player-match records):", len(player_match_df))

print("\nPosition categories:")
print(player_match_df["position"].value_counts())

print("\nMissing values in key columns:")
print(player_match_df[["player_name", "team_name", "position",
                        "goals", "assists"]].isnull().sum())
# Note: a small number of player-match rows have missing goals/assists
# (players who did not feature in that particular match). These are
# excluded automatically when summing per player, since pandas' sum()
# skips NaN values by default.


# ---------------------------------------------------------------------

# 3. DATA CLEANING & AGGREGATION TO PLAYER LEVEL
# ---------------------------------------------------------------------
# The raw dataset is at player-match level (one row per player per
# match). For this analytic task the unit of analysis is the PLAYER
# across the whole tournament, so records are aggregated by player.

player_df = (
    player_match_df
    .groupby(["player_id", "player_name", "team_name", "position"],
              as_index=False)
    .agg(
        goals=("goals", "sum"),
        assists=("assists", "sum"),
        matches_played=("match_id", "nunique")
    )
)

print("Player-level dataset shape:", player_df.shape)
print("\nPosition distribution (all players):")
print(player_df["position"].value_counts())

# Confirm no duplicate players remain after aggregation
print("\nDuplicate player_id after aggregation:",
      player_df["player_id"].duplicated().sum())


# ---------------------------------------------------------------------

# 4. FILTERING — INCLUSION / EXCLUSION CRITERIA
# ---------------------------------------------------------------------
# Inclusion rule (explicit and reproducible):
#   (a) player recorded at least one goal OR at least one assist
#       across the tournament, AND
#   (b) player's listed position is Forward or Midfielder
#
# Rationale: players with zero goal/assist involvement contribute no
# information to a comparison of attacking output, and the research
# question is specifically about Forwards vs Midfielders (Defenders
# and Goalkeepers fall outside the assigned focal point).

eligible_players = player_df[
    (player_df["goals"] > 0) | (player_df["assists"] > 0)
].copy()

print("Eligible players (>=1 goal or assist):", len(eligible_players))

analysis_df = eligible_players[
    eligible_players["position"].isin(["Forward", "Midfielder"])
].copy()

print("\nFinal analysis dataset shape:", analysis_df.shape)
print(analysis_df["position"].value_counts())
display(analysis_df.head(10))


# ---------------------------------------------------------------------

# 5. DATA PREPARATION AND SAMPLING
# ---------------------------------------------------------------------
# Population: all FIFA World Cup 2026 Forwards and Midfielders who
# recorded at least one goal or assist during the tournament.
#
# Sample: the ENTIRE eligible population is used rather than a smaller
# drawn sample, because the full set of qualifying players (n = 220)
# is available, finite, and manageable. Using the complete eligible
# group avoids introducing unnecessary sampling error and is a
# defensible approach given the data is fully accessible.

n_forward = (analysis_df["position"] == "Forward").sum()
n_midfielder = (analysis_df["position"] == "Midfielder").sum()
total_n = len(analysis_df)

print(f"Forwards:    n = {n_forward}  ({n_forward/total_n:.1%} of sample)")
print(f"Midfielders: n = {n_midfielder}  ({n_midfielder/total_n:.1%} of sample)")


# ---------------------------------------------------------------------

# 6. DESCRIPTIVE STATISTICS
# ---------------------------------------------------------------------
grouped_stats = (
    analysis_df.groupby("position")["assists"]
    .agg(n="count", mean="mean", median="median", std="std",
         min="min", max="max")
)

quartile_stats = (
    analysis_df.groupby("position")["assists"]
    .agg(Q1=lambda x: x.quantile(0.25),
         Q3=lambda x: x.quantile(0.75))
)
quartile_stats["IQR"] = quartile_stats["Q3"] - quartile_stats["Q1"]

descriptive_table = grouped_stats.join(quartile_stats)
print("Descriptive statistics — assists by position:")
display(descriptive_table)

forward_assists = analysis_df.loc[analysis_df["position"] == "Forward", "assists"]
midfielder_assists = analysis_df.loc[analysis_df["position"] == "Midfielder", "assists"]

# Boxplot comparison
plt.figure(figsize=(8, 6))
plt.boxplot([forward_assists, midfielder_assists],
            tick_labels=["Forward", "Midfielder"])
plt.title("Distribution of Total Assists by Player Position")
plt.xlabel("Player Position")
plt.ylabel("Total Assists")
plt.show()


# ---------------------------------------------------------------------

# 7. 95% CONFIDENCE INTERVALS (per group)
# ---------------------------------------------------------------------
forward_ci = stats.t.interval(
    confidence=0.95, df=len(forward_assists) - 1,
    loc=forward_assists.mean(), scale=stats.sem(forward_assists)
)
midfielder_ci = stats.t.interval(
    confidence=0.95, df=len(midfielder_assists) - 1,
    loc=midfielder_assists.mean(), scale=stats.sem(midfielder_assists)
)

print("95% Confidence Intervals for mean assists")
print(f"Forward:    mean = {forward_assists.mean():.3f}, "
      f"95% CI = ({forward_ci[0]:.3f}, {forward_ci[1]:.3f})")
print(f"Midfielder: mean = {midfielder_assists.mean():.3f}, "
      f"95% CI = ({midfielder_ci[0]:.3f}, {midfielder_ci[1]:.3f})")


# ---------------------------------------------------------------------

# 8. ASSUMPTION CHECKS
# ---------------------------------------------------------------------
# - Independence: each row is a distinct player -> satisfied.
# - Numeric DV: assists is a count variable -> satisfied.
# - Two independent groups: Forward vs Midfielder -> satisfied.
# - Normality: assists is a low, right-skewed count (many 0s/1s), so
#   a Shapiro-Wilk test is expected to reject normality. This is
#   checked below but is not disqualifying: with n > 100 per group,
#   the Central Limit Theorem means the sampling distribution of the
#   mean is approximately normal regardless of the raw data's shape.
# - Equal variances: not assumed; Welch's t-test is used, which does
#   not require equal variances between groups.

shapiro_forward = stats.shapiro(forward_assists)
shapiro_midfielder = stats.shapiro(midfielder_assists)

print("Shapiro-Wilk normality test (raw assists distribution)")
print(f"Forward:    W = {shapiro_forward.statistic:.4f}, "
      f"p = {shapiro_forward.pvalue:.2e}")
print(f"Midfielder: W = {shapiro_midfielder.statistic:.4f}, "
      f"p = {shapiro_midfielder.pvalue:.2e}")
print("\n(Both groups depart from normality, as expected for a sparse "
      "count variable. Welch's t-test is used, and with n > 100 per "
      "group the CLT supports approximate normality of the sample means.)")

print(f"\nForward variance:    {forward_assists.var():.4f}")
print(f"Midfielder variance: {midfielder_assists.var():.4f}")
# Variances are unequal, further supporting the use of Welch's test
# rather than the standard equal-variance t-test.


# ---------------------------------------------------------------------

# 9. WELCH'S INDEPENDENT TWO-SAMPLE T-TEST
# ---------------------------------------------------------------------
t_statistic, p_value = stats.ttest_ind(
    forward_assists, midfielder_assists, equal_var=False
)

# 95% CI for the difference in means (Welch-Satterthwaite)
forward_mean, midfielder_mean = forward_assists.mean(), midfielder_assists.mean()
forward_var, midfielder_var = forward_assists.var(ddof=1), midfielder_assists.var(ddof=1)
mean_difference = forward_mean - midfielder_mean

se_diff = np.sqrt(forward_var / n_forward + midfielder_var / n_midfielder)
df_welch = ((forward_var / n_forward + midfielder_var / n_midfielder) ** 2 /
            ((forward_var / n_forward) ** 2 / (n_forward - 1) +
             (midfielder_var / n_midfielder) ** 2 / (n_midfielder - 1)))
t_crit = stats.t.ppf(0.975, df_welch)
diff_ci = (mean_difference - t_crit * se_diff, mean_difference + t_crit * se_diff)

print("Welch's Independent Two-Sample t-Test")
print("--------------------------------------")
print(f"Forward mean assists:    {forward_mean:.4f}")
print(f"Midfielder mean assists: {midfielder_mean:.4f}")
print(f"Difference (F - M):      {mean_difference:.4f}")
print(f"t-statistic:             {t_statistic:.4f}")
print(f"Degrees of freedom:      {df_welch:.2f}")
print(f"p-value:                 {p_value:.4f}")
print(f"95% CI for difference:   ({diff_ci[0]:.4f}, {diff_ci[1]:.4f})")

alpha = 0.05
print("\nDecision at alpha = 0.05:")
if p_value < alpha:
    print("Reject H0 — statistically significant difference in mean "
          "assists between forwards and midfielders.")
else:
    print("Fail to reject H0 — insufficient statistical evidence of a "
          "difference in mean assists between forwards and midfielders.")

# Effect size (Cohen's d) for context alongside the p-value
pooled_sd = np.sqrt(((n_forward - 1) * forward_var +
                      (n_midfielder - 1) * midfielder_var) /
                     (n_forward + n_midfielder - 2))
cohens_d = mean_difference / pooled_sd
print(f"\nCohen's d (effect size): {cohens_d:.4f}  (small effect)")


# ---------------------------------------------------------------------

# 10. FINAL INTERPRETATION
# ---------------------------------------------------------------------
print("""
FINAL INTERPRETATION
=====================================================================
Research question: Did forwards and midfielders have a statistically
significant difference in their average number of assists among
players who recorded at least one goal or assist at the 2026 FIFA
World Cup?

Descriptive finding: Forwards recorded a higher observed mean number
of assists (M = 0.917) than midfielders (M = 0.723), a raw difference
of 0.193 assists per player.

Confidence interval finding: The 95% CI for forwards' mean assists is
approximately (0.70, 1.13); for midfielders it is approximately
(0.57, 0.88). The intervals overlap, which on its own does not prove
or disprove significance -- the formal test below is decisive.

Hypothesis-test finding: Welch's two-sample t-test gave t = 1.459,
df = 197.8, p = 0.146.

Statistical conclusion: Since p = 0.146 > alpha = 0.05, we FAIL TO
REJECT H0.

Practical conclusion: Although forwards showed a numerically higher
average number of assists than midfielders in this sample, the
difference is not large enough, relative to the variability in the
data, to conclude that forwards and midfielders differ in their true
average assist output at the 2026 FIFA World Cup. The small effect
size (Cohen's d approx 0.20) supports this: any real difference
between the positions is likely modest.
=====================================================================
""")